spring:
  application:
    name: example-spring-boot-jdbc

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3389/estate?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: xx
    password: xx


  redis:
    host: xxxxx
    port: 6379
    password: 123456

mybatis-plus:
  globalConfig:
    banner: false
    dbConfig:
      columnFormat: '`%s`'
      tablePrefix: t_

logging:
  level:
    root : INFO
    'com.lesson.boot.jdbc.mapper' : INFO



