logging:
  level:
    'com.lesson.boot.h2.mapper': trace




server:
  port: 9090
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/temp/h2
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: true
        webAllowOthers: true